package resolver

import (
	"content-services/internal/service"
)

// This file will not be regenerated automatically.
//
// It serves as dependency injection for your app, add any dependencies you require here.

type Resolver struct {
	LessonService    service.LessonService
	FlashcardService service.FlashcardService
	QuizService      service.QuizService
	TaxonomyService  service.TaxonomyService
	MediaService     service.MediaService
}

func NewResolver(
	lessonSvc service.LessonService,
	flashcardSvc service.FlashcardService,
	quizSvc service.QuizService,
	taxonomySvc service.TaxonomyService,
	mediaSvc service.MediaService,
) *Resolver {
	return &Resolver{
		LessonService:    lessonSvc,
		FlashcardService: flashcardSvc,
		QuizService:      quizSvc,
		TaxonomyService:  taxonomySvc,
		MediaService:     mediaSvc,
	}
}

// Resolver interfaces (will be generated by gqlgen)
type QueryResolver interface{}
type MutationResolver interface{}
